import { Toaster } from "react-hot-toast";

import "./globals.css";
import AuthState from "../actions/apis";
import Navbar from "@/components/navBar";

export const metadata = {
  title: "Loan App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <AuthState>
            <Navbar />
            <Toaster position="top-right" />
            {children}
          </AuthState>
        </main>
      </body>
    </html>
  );
}
