import { Toaster } from "react-hot-toast";

import "./globals.css";
import AuthState from "../actions/apis";

export const metadata = {
  title: "Loan App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Toaster position="top-right" />
          <AuthState>{children}</AuthState>
        </main>
      </body>
    </html>
  );
}
